export const profiles = [
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "H&M",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "H&M",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Grønn",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "H&M",
        price: 200,
        gender: "unisex",
        size: "82-92",
        color: "Blå",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå bukse",
        description: "Enda en perfekt bukse",
        brand: "BabyShop",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Grå",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "carl",
    id: 1,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "BabyShop",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Svart",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "BabyShop",
        price: 200,
        gender: "Jente",
        size: "92-102",
        color: "Hvit",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "102-112",
        color: "Gul",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Gucci",
        price: 200,
        gender: "Gutt",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Gucci",
        price: 200,
        gender: "Gutt",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
];
