export const profiles = [
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå lue",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå lue",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå lue",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
  {
    name: "james",
    id: 0,
    ad: [
      {
        title: "Fin rød bukse",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin gul genser",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin grønn sko",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
      {
        title: "Fin blå lue",
        description: "Enda en perfekt bukse",
        brand: "Cubus",
        price: 200,
        sex: "male",
        size: "82-92",
        color: "red",
        clothingType: "bukse",
        img: "",
      },
    ],
  },
];
