export const profiles = [
  {
    name: "james",
    profileId: 0,
    ad: [
      {
        name: "james",
        profileId: 0,
        id: 0,
        title: "Fin rød bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "H&M",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "james",
        profileId: 0,
        id: 1,
        title: "Fin gul genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "H&M",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Grønn",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "james",
        profileId: 0,
        id: 2,
        title: "Fin grønn sko",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "H&M",
        price: 200,
        gender: "unisex",
        size: "82-92",
        color: "Blå",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "james",
        profileId: 0,
        id: 3,
        title: "Fin blå bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "BabyShop",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Grå",
        clothingType: "bukse",
        img: "",
        fabric: "Ull",
        town: "Oslo",
      },
    ],
  },
  {
    name: "carl",
    profileId: 1,
    ad: [
      {
        name: "carl",
        profileId: 1,
        id: 4,
        title: "Fin rød bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "BabyShop",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Svart",
        clothingType: "bukse",
        img: "",
        fabric: "Ull",
        town: "Oslo",
      },
      {
        name: "carl",
        profileId: 1,
        id: 5,
        title: "Fin gul genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "BabyShop",
        price: 200,
        gender: "Jente",
        size: "92-102",
        color: "Hvit",
        clothingType: "bukse",
        img: "",
        fabric: "Ull",
        town: "Tromsø",
      },
      {
        name: "carl",
        profileId: 1,
        id: 6,
        title: "Fin grønn sko",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "102-112",
        color: "Gul",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Tromsø",
      },
      {
        name: "carl",
        profileId: 1,
        id: 7,
        title: "Fin blå bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Tromsø",
      },
    ],
  },
  {
    name: "Dave",
    profileId: 2,
    ad: [
      {
        name: "Dave",
        profileId: 2,
        id: 8,
        title: "Fin rød bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Gucci",
        price: 200,
        gender: "Gutt",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "Dave",
        profileId: 2,
        id: 9,
        title: "Fin gul genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Gucci",
        price: 200,
        gender: "Gutt",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "Dave",
        profileId: 2,
        id: 10,
        title: "Fin grønn sko",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "102-112",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Skien",
      },
      {
        name: "Dave",
        profileId: 2,
        id: 11,
        title: "Fin blå genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Skien",
      },
    ],
  },
  {
    name: "Durek",
    profileId: 3,
    ad: [
      {
        name: "Durek",
        profileId: 3,
        id: 12,
        title: "Fin rød bukse",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Jente",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Skien",
      },
      {
        name: "Durek",
        profileId: 3,
        id: 13,
        title: "Fin gul genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "Durek",
        profileId: 3,
        id: 14,
        title: "Fin grønn sko",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
      {
        name: "Durek",
        profileId: 3,
        id: 15,
        title: "Fin blå genser",
        description:
          "Denne buksa vil vi ikke har mer fordi de ikke passer til vår lille Georg. Den er helt burkbar. Hvis vi kommer dit så for vi se da, min venn",
        brand: "Cubus",
        price: 200,
        gender: "Gutt",
        size: "82-92",
        color: "Rød",
        clothingType: "bukse",
        img: "",
        fabric: "Bomull",
        town: "Oslo",
      },
    ],
  },
];
